sudo: false

language: node_js

node_js:
  - 5.2.0
env:
  global:
    MONGO_URL: "mongodb://localhost:27017/meteor"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  firefox: "latest"

cache:
  directories:
    - "$HOME/node_modules"
    - "$HOME/.npm"
    - "$HOME/mongodb-linux-x86_64-2.6.4"
    - "$HOME/.meteor"
    - "src/.meteor/local/build"
    - "src/.meteor/local/bundler-cache"
    - "src/.meteor/local/db"
    - "src/.meteor/local/isopacks"
    - "src/.meteor/local/plugin-cache"
    - "src/.meteor/local/mirrors"

before_cache:
  - rm -rf $HOME/build/rsercano/mongoclient/.meteor/local/log
  - rm -rf $HOME/build/rsercano/mongoclient/.meteor/local/run

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl -k https://install.meteor.com | sh; fi

  # Use X Virtual Frame Buffer
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1027x768x16"
  - sleep 3 # give xvfb some time to start
  - "export DISPLAY=:99.0"

  # Install and start MongoDB 2.6
  - export MONGO_PACKAGE=mongodb-linux-x86_64-2.6.4
  - export MONGO_HOME=$HOME/$MONGO_PACKAGE
  - if [[ ! -e $MONGO_HOME/bin/mongod ]]; then cd $HOME; wget http://downloads.mongodb.org/linux/$MONGO_PACKAGE.tgz && tar xvzf $HOME/$MONGO_PACKAGE.tgz; fi
  - export PATH=$MONGO_HOME/bin:$PATH
  - mkdir -p $HOME/data/db
  - $MONGO_HOME/bin/mongod --dbpath $HOME/data/db > $HOME/mongo.log 2>&1 &
  - cd $HOME/build/rsercano/mongoclient

  # Install NPM dependencies
  - npm install

  # Cache Velocity Meteor Release
  - .scripts/cache-velocity.js

  # Cache Selenium & ChromeDriver
  - ./node_modules/.bin/chimp --path=tests

  # Make sure Mongo has started
  - until nc -z localhost 27017 ; do echo Waiting for MongoDB; sleep 1; done

install:

script:
  - npm test